[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator_solana = "Ho3aUP4e3PtT5eBdTjcj5aoUMg5S9feMDpCrjRkHHGS8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/konstantina/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
